name: cactus
owner: galaxy-australia
description: Cactus is a reference-free whole-genome multiple alignment program
long_description: Cactus is a reference-free whole-genome multiple alignment program
categories:
- Sequence Analysis
remote_repository_url: https://github.com/usegalaxy-au/tools-au
homepage_url: https://github.com/ComparativeGenomicsToolkit/cactus
type: unrestricted
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "{{ tool_name }} from the cactus suite"
suite:
  name: suite_cactus
  description: Cactus is a reference-free whole-genome multiple alignment program
  long_description: Cactus is a reference-free whole-genome multiple alignment program
exclude:
  - help.md
  - README.md
  - tool_test_output.html
  - tool_test_output.json
  