---
categories:
    - Metagenomics
description: A flexible pipeline for genome-resolved metagenomic data analysis
exclude:
    - extras
    - README.md
    - tool_test_output.html
    - tool_test_output.json
homepage_url: https://github.com/bxlab/metaWRAP
long_description: |
    A convenient wrapper around three metagenomic binning software: MaxBin2,
    metaBAT2, and CONCOCT. Bin refinement utilizes a hybrid approach to take
    in two or three bin sets that were obtained with different software and
    produces a consolidated, improved bin set.
name: metawrapmg_binning
owner: galaxy-australia
remote_repository_url: https://github.com/usegalaxy-au/tools-au/tree/master/tools/metawrapmg
type: unrestricted
